version: '3.7'

services:
  couchdb:
    image: couchdb:3.3.2
    container_name: couchdb
    restart: unless-stopped
    ports:
      - '127.0.0.1:5984:5984'
      - '127.0.0.1:4369:4369'
      - '127.0.0.1:9100:9100'
    # env_file: .env
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
        - ./data:/opt/couchdb/data
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
  app:
    build: .
    image: wiserswap
    container_name: wiserswap
    restart: unless-stopped
    # network_mode: 'host'
    ports:
      - '127.0.0.1:3000:3000'
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    environment:
      - API_ENDPOINT=${API_ENDPOINT}
