services:
  app:
    build: .
    image: wiserswap
    container_name: wiserswap
    restart: unless-stopped
    ports:
      - '127.0.0.1:3000:3000'
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    environment:
      - NUXT_ENV_API_ENDPOINT=${API_ENDPOINT}
      - NUXT_ENV_API_ENDPOINT_TEST=API_TEST_ENDPOINT
